services:
  fahrgemeinschaften:
    container_name: spotidown
    image: spotidown:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
      - ./music:/music #map to the navidrome musicfolder
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge