services:
  spotidown:
    container_name: spotidown
    image: spotidown:latest
    network_mode: host
    ports:
      - 5001:5000
    volumes:
      - ./music:/music #map to the navidrome musicfolder
    restart: unless-stopped
