services:
  spotidown:
    container_name: spotidown
    image: spotidown:latest
    ports:
      - 5001:5000  # Map the host's port 5001 to container's port 5000
    volumes:
      - ./music:/music  # Map the music folder
    restart: unless-stopped